on:
  schedule:
    - cron: '0 * * * *' # runs the aggregation every hour

jobs:
  aggregate:
    runs-on: ubuntu-latest
    name: Automatic datasets generation
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: aggregation
      uses: ch-covid-19/data-github-action@master
      with:
          daily_export_json_url: https://asia-east2-covid19-india-54007.cloudfunctions.net/daily_json
          geo_locations_csv_url: https://raw.githubusercontent.com/ch-covid-19/geo-locations/master/data/ind/ind_geocoding.csv
          daily_report_name: 'daily-changes/{date}.csv'
          daily_export_json_token: ${{ secrets.readToken }}
          # Put other variables value here if you want
    - name: Commit changes
      run: |
          git config --local user.email "prabhakaran1989@gmail.com"
          git config --local user.name "Prabhakaran Kasinathan GitHub Action"
          git add .
          git commit -m "performed automatic github datasets generation"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
